name: Create a (Pre)release on NuGet

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-dotnet-8"  # Match pre-release tags like 1.0.29-dotnet-8
      - "v[0-9]+.[0-9]+.[0-9]+-dotnet-8" # Match pre-release tags like v1.0.29-dotnet-8

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify your .NET version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: 'YOUR_AWS_REGION' # e.g., us-east-1

      - name: Restore dependencies
        run: dotnet restore
      
      - name: Use the pushed tag (Push trigger)
          id: get_version_from_push
          uses: battila7/get-version-action@v2

      - name: Pack project
        run: |
            version_without_v=${{ steps.get_version_from_push.outputs.version-without-v }}
            dotnet pack src/Indiko.Maui.Controls.Markdown -c Release -p:PackageVersion=$version_without_v
        shell: bash
 
      - name: Get CodeArtifact Authorization Token
        id: codeartifact_token
        run: |
          echo "token=$(aws codeartifact get-authorization-token --domain flowns --domain-owner 949880251768 --query authorizationToken --output text)" >> $GITHUB_ENV

      - name: Push to AWS CodeArtifact
        run: |
          dotnet nuget push ./packages/*.nupkg \
            --source https://flowns-949880251768.d.codeartifact.eu-north-1.amazonaws.com/nuget/nuget/v3/index.json \
            --api-key ${{ env.token }}
  