name: Create a (Pre)release on NuGet

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-dotnet-8"  # Match pre-release tags like 1.0.29-dotnet-8
      - "v[0-9]+.[0-9]+.[0-9]+-dotnet-8" # Match pre-release tags like v1.0.29-dotnet-8
  workflow_dispatch:    # Allows manual run

jobs:
  build-and-publish:
    runs-on: macos-latest
    permissions:
      id-token: write # Required for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: |
          git fetch --tags
        shell: bash

      - name: Get latest tag (Manual trigger)
        if: github.event_name == 'workflow_dispatch'
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          latest_tag_without_v=${latest_tag#v}
          echo "latest_tag=$latest_tag_without_v" >> $GITHUB_ENV
        shell: bash

      - name: Use the pushed tag (Push trigger)
        if: github.event_name == 'push'
        id: get_version_from_push
        uses: battila7/get-version-action@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify your .NET version

      - name: Install MAUI workloads
        run: dotnet workload restore src/Indiko.Maui.Controls.Markdown/Indiko.Maui.Controls.Markdown.csproj

      - name: Restore dependencies
        run: dotnet restore src/Indiko.Maui.Controls.Markdown/Indiko.Maui.Controls.Markdown.csproj

      - name: Pack project
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            dotnet pack src/Indiko.Maui.Controls.Markdown/Indiko.Maui.Controls.Markdown.csproj -c Release -p:PackageVersion=${{ env.latest_tag }} --output ./packages
          else
            version_without_v=${{ steps.get_version_from_push.outputs.version-without-v }}
            dotnet pack src/Indiko.Maui.Controls.Markdown/Indiko.Maui.Controls.Markdown.csproj -c Release -p:PackageVersion=$version_without_v --output ./packages
          fi
        shell: bash
 
      - name: Push to AWS CodeArtifact
        id: codeartifact_token
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }}
          export AWS_REGION=eu-north-1
          aws codeartifact login --tool dotnet --domain flowns --domain-owner 949880251768 --repository nuget
          dotnet nuget push ./packages/*.nupkg --source flowns/nuget
          
  